### ISSUE TITLE
Can not specify to run tests on groups

### ISSUE THREAD

**Issue by dommistry** [robertgates55/frameworkium#1]
If I try to make a group for one of the tests by doing the following:
Write the following in the @Test() above my test method:
Groups={"Dom"}
so it reads:
@Test(Groups={"Dom"})

Then:
Clicking on the drop down arrow next to run > run configurations > inside the goals box typing clean verify > click add > in the Name box I type groups > in the value box I type Dom > click ok > click apply > click run

This time the results fail with Creation Guice creation errors

The top line of the error in the console is as follows:

Sep 10, 2015 8:38:40 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.langNullpointerException
java.lang.NullPointerException
      At com.frameworkium.tests.internal.BaseTest.getDriver(BaseTest.java:130)
     -A lot more errors below

I think something that needs to install doesn't install when I try to run groups instead of all the tests. But I'm not sure what this is or where to put it.

Thanks.

**Comment by robertgates55** [comment]
Resolved by v1.1.4 of frameworkium-core.

Have updated the frameworkium master pom to bump this.
